const { CRYPTO_QUANTITY_LOCKED_TILL } = process.env;

module.exports = {
  STATUS_CODE: {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    INFO: 250,
    BAD_REQUEST: 400,
    UN_AUTHORIZED: 401,
    FORBIDDEN: 403,
    RESOURCE_NOT_FOUND: 404,
    PROXY_AUTH_FAILED: 412,
    TOO_MANY_REQUESTS: 429,
    VALIDATION_FAILURE: 450,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    SERVER_TIMEOUT: 504,
  },
  ERROR_MSGS: {
    ADMIN_KEYS_NOT_FOUND: 'Admin details not found.',
    USER_ACCOUNT_BLOCKED: 'Please try again later.',
    AUTH_FAIL: 'Authentication failed.',
    INTERNAL_SERVER_ERROR: 'Unable to process,Please Try Again',
    INVALID_ROUTE: 'Requested API route is not available.',
    USERNAME_EXISTS: 'User name already exists. Try a different name',
    USERNAME_ALREADY_SET: 'Username is already set.',
    EMAIL_EXISTS: 'Email already added with another wallet address.',
    SIGN_VERIFY_FAILED: 'Signature verification failed',
    NONCE_EMPTY: 'Please get new nonce value.',
    NONCE_NOT_CREATED: 'Nonce not created for the address.',
    NONCE_EXPIRED: 'Nonce has expired, please try with new one.',
    ACCOUNT_EXISTS: 'Account already exists. Please login',
    ACCOUNT_NOT_FOUND: 'Account not found, related to the given email.',
    ACCOUNT_BLOCKED:
      'Your account has been blocked, please reach out to our support',
    ACCOUNT_LOCKED:
      'Your account has been blocked, please use forgot password option to reset password and login.',
    ACCOUNT_LOCKED_EMAIL_TRIGGERED:
      'Your account has been blocked, mail has been triggered to reset password.',
    IP_LOCKED: 'Please try again later.',
    ACCOUNT_DISABLED:
      'Your account has been disabled, please reach out to our support',
    USER_NOT_FOUND: 'User not found',
    INVALID_LOGIN: 'Invalid email or/and password.',
    WALLET_NOT_FOUND: 'Account not found, related to the given wallet.',
    LOGIN_WITH_EMAIL: 'Please login with Email and password',
    LOGIN_WITH_GOOGLE: 'Please login with Google',
    LOGIN_WITH_METAMASK: 'Please login with Metamask',
    FORGOT_PASSWORD_TOKEN_EXPIRED: 'Token has expired.',
    TOKEN_MISSING: 'No token provided',
    TOKEN_SESSION_EXPIRED: 'Token Session Expired',
    INVALID_TOKEN_FORMAT: 'Token invalid format',
    INVALID_TOKEN_TYPE: 'Invalid Token type',
    INVALID_CODE: 'Invalid Code',
    INVALID_TOKEN_ID: 'Invalid Token Id',
    TWO_FACTOR_ENABLED: '2FA already enabled',
    TWO_FACTOR_DISABLED: '2FA already disabled',
    TWO_FACTOR_NOT_ENABLED: '2FA is not enabled for this account',
    TWO_FACTOR_NOT_CONFIGURED: '2FA is not configured',
    TWO_FACTOR_SETUP_COMPLETED: '2FA setup already completed.',
    TWO_FACTOR_ENABLING_REQUIRED: 'Please enable 2FA to proceed further.',
    GOOGLE_AUTHENTICATION_FAILED:
      'Google authentication failed. Please try again.',
    FILE_REQUIRED: 'Please upload the required file.',
    FILE_ARRAY_TYPE: 'File should be of type array',
    ITEM_FILE_MAX_LIMIT_EXCEED: 'Can only add 5 or less than files for a item.',
    SINGLE_FILE_ONLY_ALLOWED:
      'Only single file upload is supported for audio and video and gif files types',
    SUBSCRIPTION_DISABLED: 'Subscription is disabled.',
    SUBSCRIPTION_ALREADY_EXISTS: 'Already subscribed.',
    INVALID_FILE_TYPE: 'Invalid file format',
    INVALID_FILE_SIZE: 'File should be below 4MB',
    INVALID_CAREER_FILE_SIZE: 'File should be below 5MB',
    COLLECTION_NOT_FOUND: 'Collection Not found',
    COLLECTION_DISABLED: 'Collection is disabled',
    EMAIL_VERFICATION_NOT_NEEDED:
      'Email Verification is not required for Google and Metamask registration',
    CHANGE_PASSWORD_NOT_ALLOWED:
      'Password reset option is not available for Google and Metamask registration',
    OLD_PASSWORD:
      'You have entered an old password. Please try a different password',
    INCORRECT_PASSWORD: 'Invalid Password',
    KYC_ALREADY_VERIFIED: 'KYC is already verified.',
    KYC_ALREADY_SUBMITTED: 'KYC is already submitted.',
    KYC_REJECTED: 'KYC is rejected.',
    KYC_SUBMITTED: 'KYC submitted successfully',
    KYC_VERIFICATION_REQUIRED:
      'KYC verification is required to proceed further.',
    PROFILE_STATUS_PRIVATE: 'Profile is already in private mode.',
    PROFILE_STATUS_PUBLIC: 'Profile is already in public mode.',
    ITEM_NOT_FOUND: 'Item not found',
    ITEM_DISABLED: 'Item is disabled',
    REQUESTED_ITEM_QUANTITY_NOT_AVAILABLE:
      'Please try with lesser quantity as request quantity is not available.',
    OWNER_NOT_ALLOWED_REQUEST_OFFER:
      'You are not to allowed request offer for your own item.',
    SALE_NOT_FOUND: 'Sale not found',
    SALE_DISABLED: 'Sale is disabled',
    SALE_CLOSED: 'Sale is closed',
    SALE_CANCELLED: 'Sale is closed',
    SALE_ACCEPT_ONLY_FIAT: 'Sale can accept only fiat buy.',
    SALE_ACCEPT_ONLY_CRYPTO: 'Sale can accept only crypto buy.',
    INVALID_ITEM_OWNER: 'You are not an owner for this item',
    ITEM_QUANTITY_LEVEL_REACHED: `You don't have enough quantity`,
    SELLER_ITEM_QUANTITY_LEVEL_REACHED: `Seller don't have enough quantity`,
    SELLER_NOT_ALLOWED: 'You are not allowed buy your own sale.',
    ALREADY_CREATED_WITHDRAWAL_ACCOUNT:
      'You have already created an withdrawal account.',
    WITHDRAWAL_ACCOUNT_NOT_ADDED: 'Withdrawal account details not yet added.',
    WITHDRAWAL_ACCOUNT_DISABLED: 'Withdrawal account has been disabled',
    BANK_ACCOUNT_NOT_FOUND: 'Bank account not found, related to the given id.',
    CRYPTO_ALREADY_CREATED_WITHDRAWAL_ACCOUNT:
      'You have already created an crypto withdrawal account.',
    CRYPTO_WITHDRAWAL_ACCOUNT_NOT_ADDED:
      'Crypto withdrawal account details not yet added.',
    CRYPTO_WITHDRAWAL_ACCOUNT_DISABLED:
      'Crypto withdrawal account has been disabled',
    CRYPTO_WITHDRAWAL_ALREADY_EXISTS:
      'Crypto withdrawal account already added.',
    CRYPTO_ACCOUNT_NOT_FOUND: 'Account not found, related to the given id.',
    ADDRESS_NOT_FOUND: 'Address not found, related to the given id.',
    FIAT_WALLET_NOT_CREATED: 'Fiat wallet not yet created.',
    FIAT_WALLET_NOT_FOUND: 'Fiat wallet not found.',
    CRYPTO_WALLET_NOT_CREATED: 'Crypto wallet not yet created.',
    CRYPTO_WALLET_NOT_FOUND: 'Crypto wallet not found.',
    CRYPTO_WALLET_DISABLED: 'Crypto wallet is disabled.',
    CRYPTO_WALLET_LOCKED_INSUFFICIENT:
      'Crypto wallet locked balance is insufficient.',
    CRYPTO_WALLET_FREE_INSUFFICIENT:
      'Crypto wallet free balance is insufficient.',
    CRYPTO_WALLET_INSUFFICIENT: 'Crypto wallet balance is insufficient.',
    FIAT_WALLET_LOCKED_INSUFFICIENT:
      'Fiat wallet locked balance is insufficient.',
    FIAT_WALLET_LOCKED_INSUFFICIENT_CANNOT_CANCEL:
      'Unable to cancel earlier bid, please contact support.',
    FIAT_WALLET_FREE_INSUFFICIENT: 'Fiat wallet free balance is insufficient.',
    FIAT_WALLET_FEE_INSUFFICIENT: 'Fiat wallet balance is insufficient.',
    FIAT_WALLET_DISABLED: 'Fiat wallet is disabled.',
    FREE_BALANCE_INSUFFICIENT:
      'Insufficient free balance to request withdrawal.',
    WITHDRAWAL_REQUEST_NOT_FOUND: 'Withdrawal request not found.',
    LISTING_NOT_FOUND: 'Sale not found',
    PAYMENT_PROCESSING: 'Payment is under process, please contact support.',
    PAYMENT_FAILED: 'Payment failed, please contact support.',
    SALE_ALREADY_POSTED:
      'Please cancel the previous sale listing and raise a new one',
    AUCTION_NOT_FOUND: 'Auction not found',
    AUCTION_DISABLED: 'Auction is disabled.',
    CANNOT_BID_OWN_ACTION: 'You cannot bid your own auction.',
    AUCTION_CLOSED: 'Auction is closed.',
    AUCTION_TIME_OVER:
      'You cannot perform the operation because auction is going to execute in less than few minutes',
    BID_LESS_THAN_MINIMUM:
      'Bid should be greater than the minimum price amount.',
    BID_CANT_BE_CANCELLED: `You can't cancel the auction because it has active bids`,
    BID_HIGHEST_AMOUNT:
      'Bid amount should be greater than the highest available bid amount.',
    UNABLE_TO_CANCEL_HOLD_AMOUNT:
      'Unable to cancel tha amount held for auction in card.',
    CAN_BID_AUCTION_SALE_ONLY:
      'Unable to post bid, as it is not a auction type sale.',
    CANCEL_BID_AUCTION_SALE_ONLY:
      'Unable to cancel bid, as it is not a auction type sale.',
    PAYMENT_CANCELLED: 'Payment is cancelled, please contact support.',
    STRIPE_PAYMENT_HOLD_ERROR: 'Payment processing failed, please try again.',
    STRIPE_PAYMENT_ID_REQUIRED: 'Payment Id is required.',
    CRYPTO_TRANSACTION_HASH_REQUIRED: 'Crypto transaction hash is required.',
    BID_NOT_FOUND: 'Bid not found.',
    NO_SALE_QUANTITY_AVAILABLE: 'No quantity available for buy.',
    NO_SALE_QUANTITY_AVAILABLE_LOCKED: 'No locked quantity available for buy.',
    USER_METAMASK_LOGIN_REQUIRED: 'User should login with metamask account.',
    BUYER_METAMASK_BALANCE_INSUFFICIENT:
      'Insufficient ether balance in metamask account.',
    BID_ALREADY_CANCELLED: 'Bid is cancelled already.',
    INVALID_CAPTCHA: 'Invalid captcha',
    PROFILE_ALREADY_PUBLIC: 'Profile is already public',
    PROFILE_ALREADY_PRIVATE: 'Profile is already private',
    PROFILE_PRIVATE: 'The requested profile is in private mode',
    INVALID_CATEGORY: 'Invalid category',
    INVALID_ITEM_CATEGORY: 'Invalid item category',
    ITEM_SUPPORTED_FORMATS:
      'Supported formats are jpg, png, gif, svg, mp4, mp3, webm, wav, ogg, glb, gltf',
    LOGO_REQUIRED: 'Logo is required',
    FILE_REQUIRED: 'File is required',
    INVALID_FILE_SIZE: 'File size should be less than 40 MB',
    INVALID_LOGO_SIZE: 'Logo size should be less than 10 MB',
    INVALID_BACKGROUND_PICTURE_SIZE:
      'Background picture size should be less than 10 MB',
    INVALID_FILE_IMAGE_SIZE: 'File size should be less than 10 MB',
    INVALID_IMAGE_MIME_TYPE: 'Supported formats are jpeg, jpg and png',
    NOT_VERIFIED: 'Account not verified',
    BACKGROUND_IMG_REQUIRED: 'Background image is required',
    ALREADY_FOLLOWING: 'Already following.',
    NOT_FOLLOWING: 'Not following.',
    CANNOT_FOLLOW: 'Cannot follow your own account.',
    AMOUNT_GREATER_THAN_ZERO: 'Amount must be greater than 0',
    TYPE_REQUIRED: 'Type is required.',
    TYPE_SHOULD_BE: 'Type should be fiat or crypto.',
    SELLER_WITHDRAWAL_ADDRESS_NOT_FOUND: 'Seller withdrawal address not found.',
    CURRENCY_HOLDING_EXPIRED: 'Amount locking period has expired.',
    MIN_CRYPTO_SALE_AMOUNT: 'Crypto sale amount is lesser than minimum price.',
    HOLDING_ID_REQUIRED: 'Holding Id is required',
    QUANTITY_LOCKED_IN_CRYPTO_BUY: `Quantity is locked. Please check after 24 hours`,
    NOT_AN_OWNER: 'You are not owner of this item',
    DONT_HAVE_ENOUGH_QUANTITY_FOR_EXPORT: `You don't have enough quantity`,
    INVALID_ADDRESS: 'Invalid address',
    INVALID_REQUEST_ID: 'Invalid Request Id',
    PHYSICAL_NFT_NOT_AVAILABLE: 'Physical nft not available',
    EXPORT_PAYMENT_ID_EXISTS:
      'Payment Id has already added, please complete new payment and try again.',
    IMPORT_TXN_ID_EXISTS: 'Import transaction Id already exists.',
    NO_QUANTITIES_EXPORTED_FOR_IMPORT:
      'NFTs are not exported for the given tokenId to import.',
    PLEASE_PROVIDE_AVAILABLE_QUANTITY_TO_IMPORT:
      'From address have less quantity of NFT than requested quantity of NFT to import',
    BID_TRANSACTION_ALREADY_ADDED: 'Given crypto transaction already added.',
    OFFER_PAYMENT_ID_EXISTS:
      'Payment Id has already added, please complete new payment and try again.',
    OFFER_TRANSACTION_ALREADY_ADDED: 'Given crypto transaction already added.',
    CHECK_THE_SALE_TYPE: 'Please check the sale type.',
    OFFER_NOT_FOUND: 'Invalid offer Id',
    OFFER_INACTIVE: 'Offer is not in active state',
    INVALID_ACCEPTANCE: 'You are not allowed to accept your own offer.',
    PAYMENT_NOT_CONFIRMED: 'Payment not confirmed',
    INVALID_ID: 'Invalid Id',
    AMOUNT_SHOULD_BE_GREATER: 'Amount should be greater than zero',
    STRIPE_MAX_PRICE_REACHED: `Please try with lesser amount as maximum amount accepted in single payment is less than $${process.env.STRIPE_MAX_PRICE}.`,
    STRIPE_MIN_PRICE_NOT_REACHED: `Please try with larger amount as minimum amount accepted is greater than $${process.env.STRIPE_MIN_PRICE}.`,
    OWNER_DO_NOT_HAVE_THIS_EDITION: 'You does not own the edition.',
    EDITIONS_NOT_EQUAL_QUANTITY: 'Editions chosen does not equal the quantity.',
    AVAILABLE_EDITION_QUANTITY_NOT_MATCH:
      'Available edition quantities does not match the required.',
    SALE_DO_NOT_HAVE_THIS_EDITION: 'Sale does not have the given edition.',
    INVALID_OWNER: 'Invalid owner',
    INVALID_EDITION: 'Selected edition is not valid',
    EDITION_IS_LOCKED: 'Selected edition is locked',
    CANNOT_ACT_ON_OFFER: 'You dont have privileges to act on the offer',
    EDITION_NOT_AVAILABLE: 'Edition not available',
    CANNOT_OFFER_OWN_ITEM: 'Cannot post offer for yourself.',
    NOT_ENOUGH_QUANTITY: 'You dont have enough quantity',
    EXISTS_AS_PRIMARY_EMAIL: 'Email already in use as primary email.',
  },
  INFO_MSGS: {
    NO_DATA: 'No data found',
    CREATED_SUCCESSFULLY: 'Created successfully',
    SUCCESS: 'Request Success',
    BETA_REGISTER:
      'Your registration with fantico is successful. Please check your email for credentials',
    SUCCESSFUL_REGISTER: 'Your registration with fantico is successful.',
    SUCCESSFUL_UPDATE: 'Successfully updated',
    WELCOME_MSG: 'Welcome to Client API Services.',
    SUCCESSFUL_LOGIN: 'Successfully logged in.',
    SUCCESSFUL_ENABLE: '2FA enabling requested successfully.',
    SUCCESSFUL_RESET: '2FA is successfully reset on your request.',
    PASSWORD_CHANGED: 'Your password has been changed successfully.',
    VERIFICATION_EMAIL: 'Verification Email send successfully.',
    EMAIL_NOT_VERIFIED: 'Email not verified, Please verify it.',
    EMAIL_VERIFIED: 'Email already Verified. Please login',
    EMAIL_SEND: 'Email sent to the registered account.',
    ACCOUNT_VERIFIED: 'Your account has been verified, Please login.',
    TWO_FACTOR_SUCCESS: 'Successfully configured 2FA',
    TWO_FACTOR_ENABLED: '2FA enabled successfully',
    TWO_FACTOR_DISABLED: '2FA disabled successfully',
    SUCCESSFUL_LOGOUT: 'Successfully logged out.',
    USERNAME_AVAILABLE: 'Username available',
    USERNAME_NOT_AVAILABLE: 'Username not available',
    PROFILE_STATUS_PRIVATE: 'Successfully updated profile to private mode.',
    PROFILE_STATUS_PUBLIC: 'Successfully updated profile to public mode.',
    COLLECTION_NAME_AVAILABLE: 'Collection Name available',
    COLLECTION_NAME_NOT_AVAILABLE: 'Collection Name not available',
    COLLECTION_NOT_AVAILABLE: 'Collection not available',
    NO_COLLECTIONS: 'No Collections available',
    ITEMS_NOT_AVAILABLE: 'No items available',
    ITEMS_NOT_AVAILABLE_SEARCH:
      'No items in the collection for the given search',
    WITHDRAWAL_ACCOUNT_ADDED: 'Withdrawal account added successfully',
    WITHDRAWAL_ACCOUNT_UPDATED: 'Withdrawal account updated successfully',
    WITHDRAWAL_ACCOUNT_DELETE: 'Withdrawal account deleted successfully',
    CRYPTO_WITHDRAWAL_ACCOUNT_ADDED:
      'Crypto withdrawal account added successfully',
    CRYPTO_WITHDRAWAL_ACCOUNT_UPDATED:
      'Crypto withdrawal account updated successfully',
    WITHDRAWAL_REQUEST_CREATED: 'Withdrawal request submitted successfully.',
    NO_WITHDRAWAL_REQUESTS: 'Withdrawal requests not available.',
    SALE_POSTED: 'Sale Posted successfully',
    CANCELLED_SUCCESSFULLY: 'Cancelled successfully',
    BUY_INITIATE_SUCCESS: 'Buy initiated successfully.',
    BID_INITIATE_SUCCESS: 'Bid initiated successfully.',
    NO_TRANSACTIONS_AVAILABLE: 'No Transactions Available',
    SUBSCRIBED_SUCCESSFULLY: 'Subscribed successfully.',
    BID_COMPLETED: 'Bid completed successfully.',
    BID_CANCELLED_SUCCESSFULLY: 'Bid cancelled successfully.',
    BUY_COMPLETED: 'Buy completed successfully.',
    NO_AUCTIONS: 'No auctions available.',
    REPORTED: 'Reported successfully',
    ITEM_NAME_NOT_AVAILABLE: 'Item Name not available',
    ITEM_NAME_AVAILABLE: 'Item Name available',
    NO_ACTIVITIES_FOUND: 'No Activities found',
    UN_FOLLOW_SUCCESS: 'Un-followed the user successfully.',
    FOLLOW_SUCCESS: 'Your now following the user.',
    CRYPTO_PAYMENT_RECEIVED:
      'Your order will be executed after the payment confirmation',
    EXPORT_REQUEST_SUCCESS: 'Export request successfully created',
    CELEBRITIES_NOT_FOUND: 'Celebrities not found',
    ARTISTS_NOT_FOUND: 'Artists not found',
    KYC_SUBMITTED: 'KYC submitted successfully',
    SURVEY_SUBMITTED: 'Survey reponse submitted successfully.',
    ADDRESS_ADDED: 'Address added successfully',
    ADDRESS_UPDATED: 'Address updated successfully',
    ADDRESS_DELETED: 'Address deleted successfully',
    ADDRESS_NOT_ADDED: 'Address not added',
    ADDRESS_NOT_FOUND: 'Address not found',
    REQUEST_INITIATED: 'Successfully initiated request',
    REQUEST_INFO_NOT_FOUND: 'No requests found',
    PAYMENT_RECEIVED: 'Payment received',
    NFT_OFFER_INITIATED_SUCCESSFULLY: 'NFT offer initiated successfully.',
    NFT_OFFER_POSTED_SUCCESSFULLY: 'NFT offer posted  successfully.',
    OFFER_ACCEPTED: 'Successfully accepted offer',
    OFFERS_NOT_AVAILABLE: 'No offers available.',
    THANKYOU_FOR_CONTACTING:
      'Thank you for contacting us. Our support team will reach you within 24 hours over email.',
    APPLIED_FOR_JOB: 'Successfully applied for the position',
    ADDED_AS_FAVOURITE: 'Successfully updated favourites',
    VIEW_ADDED: 'Successfully updated view',
    ALREADY_VIEWED: 'You have already viewed the NFT',
    SECONDARY_EMAIL_ADDED_SUCCESSFULLY: 'Secondary email added successfully.',
    SECONDARY_EMAIL_REMOVED_SUCCESSFULLY:
      'Secondary email removed successfully.',
    IMPORT_REQUEST_PLACED: 'Import Request placed successfully',
  },
};
